# Generated by Django 4.2.1 on 2024-01-31 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='KES', max_length=20)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitem', to='invoice.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
